import { ReactNode } from "react";
import type { Metadata } from "next";
import ReduxProvider from "@/store/ReduxProvider";
import Navbar from "@/layout/Navbar";

import "./globals.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: ReactNode;
};

const RootLayout = (props: Props) => {
  const { children } = props;

  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <Navbar />
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
};

export default RootLayout;
